# Generated by Django 2.1 on 2019-09-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
