# Generated by Django 2.1 on 2019-09-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20190925_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('is_percentage', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupon.Discount'),
            preserve_default=False,
        ),
    ]
