# Generated by Django 2.1.3 on 2019-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='문의', max_length=200),
        ),
    ]
