# Generated by Django 2.1 on 2019-09-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
