# Generated by Django 2.1.3 on 2019-08-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.TextField(blank=True)),
            ],
        ),
    ]
