# Generated by Django 2.1.3 on 2019-08-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
