# Generated by Django 2.1 on 2019-09-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
