# Generated by Django 2.1.3 on 2019-08-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190821_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
