# Generated by Django 2.1 on 2019-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_comment_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_thumbnail_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='tite',
            field=models.CharField(db_index=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
