# Generated by Django 2.1.3 on 2019-08-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190812_1424'),
        ('shop', '0004_auto_20190809_1136'),
    ]

    operations = [
    ]
