# Generated by Django 2.1.10 on 2019-08-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190828_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
