# Generated by Django 2.1.3 on 2019-08-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190814_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('content', models.ImageField(upload_to='')),
            ],
        ),
    ]
