# Generated by Django 2.1.3 on 2019-08-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190819_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe_content',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe_title_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
