# Generated by Django 2.1.3 on 2019-08-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190819_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipe_title_image',
        ),
    ]
