# Generated by Django 2.1.3 on 2019-08-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_recipe_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe_content',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
