# Generated by Django 2.1.3 on 2019-08-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190819_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe_content',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
