# Generated by Django 2.1.3 on 2019-08-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190819_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe_content',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
