# Generated by Django 2.1.10 on 2019-09-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, null=True)),
                ('before_verified', models.CharField(max_length=16, null=True)),
                ('verification_code', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='coupon',
        ),
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(to='coupon.Coupon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(default='000-0000-0000', on_delete=django.db.models.deletion.CASCADE, to='members.Phone'),
        ),
    ]
