# Generated by Django 2.1.10 on 2019-09-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190906_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Phone'),
        ),
    ]
