# Generated by Django 2.1 on 2019-09-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='username',
        ),
    ]
