# Generated by Django 2.1.10 on 2019-09-30 06:07

from django.db import migrations, models
import members.CertiNum


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190925_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssend',
            name='msg_text',
            field=models.CharField(default=members.CertiNum.get_centification_number, max_length=4),
        ),
    ]
