# Generated by Django 2.1.10 on 2019-09-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190930_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssend',
            name='msg_text',
            field=models.CharField(max_length=4),
        ),
    ]
