# Generated by Django 2.1 on 2019-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_address_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('sms', 'sms')], default='sms', max_length=3)),
                ('msg_getter', models.CharField(max_length=20)),
                ('msg_sender', models.CharField(default='01056373374', max_length=20)),
                ('msg_text', models.TextField()),
            ],
        ),
    ]
