# Generated by Django 2.1.10 on 2019-10-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190930_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssend',
            name='msg_confirm',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
