# Generated by Django 2.1 on 2019-10-01 03:49

from django.db import migrations, models
import members.CertiNum


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_smssend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssend',
            name='msg_text',
            field=models.CharField(default=members.CertiNum.get_centification_number, max_length=4),
        ),
    ]
