# Generated by Django 2.1.10 on 2019-10-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_smssend_msg_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssend',
            name='msg_confirm',
        ),
    ]
