# Generated by Django 2.1 on 2019-09-09 07:28

from django.db import migrations, models
import order.orderNumber


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='addr1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='addr2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='zip',
        ),
        migrations.AddField(
            model_name='order',
            name='orderno',
            field=models.CharField(default=order.orderNumber.get_order_code, max_length=18),
        ),
    ]
