# Generated by Django 2.1 on 2019-09-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('order', '0002_auto_20190909_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Option'),
            preserve_default=False,
        ),
    ]
